I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/labels/capitulo_1/escena_02.rpy", line 6, in script
    python:
ScriptError: could not find label 'cap01_escena03'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "F:\PROGRAMACIO\renpy-6.18.3-sdk\renpy\bootstrap.py", line 289, in bootstrap
    renpy.main.main()
  File "F:\PROGRAMACIO\renpy-6.18.3-sdk\renpy\main.py", line 357, in main
    run(restart)
  File "F:\PROGRAMACIO\renpy-6.18.3-sdk\renpy\main.py", line 77, in run
    renpy.execution.run_context(True)
  File "F:\PROGRAMACIO\renpy-6.18.3-sdk\renpy\execution.py", line 598, in run_context
    context.run()
  File "game/labels/capitulo_1/escena_02.rpy", line 6, in script
    python:
  File "F:\PROGRAMACIO\renpy-6.18.3-sdk\renpy\script.py", line 595, in lookup
    raise ScriptError("could not find label '%s'." % str(label))
ScriptError: could not find label 'cap01_escena03'.

Windows-post2008Server-6.2.9200
Ren'Py 6.18.3.761
Reus Quest PreAlpha 0.0.1 0.0
